// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lazy_mouse_windows
void lazy_mouse_windows(int total_seconds);
RcppExport SEXP _LazyMouse_lazy_mouse_windows(SEXP total_secondsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type total_seconds(total_secondsSEXP);
    lazy_mouse_windows(total_seconds);
    return R_NilValue;
END_RCPP
}
// lazy_mouse_macos
void lazy_mouse_macos(int pixels);
RcppExport SEXP _LazyMouse_lazy_mouse_macos(SEXP pixelsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type pixels(pixelsSEXP);
    lazy_mouse_macos(pixels);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LazyMouse_lazy_mouse_windows", (DL_FUNC) &_LazyMouse_lazy_mouse_windows, 1},
    {"_LazyMouse_lazy_mouse_macos", (DL_FUNC) &_LazyMouse_lazy_mouse_macos, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_LazyMouse(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
