# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prevent_idle_windows <- function(seconds) {
    invisible(.Call(`_LazyMouse_prevent_idle_windows`, seconds))
}

move_mouse_random <- function(pixels = 50L) {
    invisible(.Call(`_LazyMouse_move_mouse_random`, pixels))
}

